import type { SceneKind } from "@/components/art/Scene";

/**
 * Görsel yuvası manifesti.
 *
 * `src` tanımlanana kadar markaya özgü SVG sahne (yer tutucu, dekoratif) gösterilir.
 * Gerçek fotoğraf eklemek için:
 *   1. Dosyayı `public/images/` altına koyun (JPG/PNG/WebP; Next.js AVIF/WebP'ye çevirir).
 *   2. İlgili satıra `src: "/images/xyz.jpg", width: <px>, height: <px>` ekleyin.
 *   3. `alt` metni gerçek fotoğrafı betimlemeli; aşağıdaki değerler çekim brief'i niteliğindedir.
 * Çekim brief'leri ve oranlar: docs/IMAGE-BRIEF.md
 */
export type Slot = { scene: SceneKind; alt: string; src?: string; width?: number; height?: number };

export const SLOTS: Record<string, Slot> = {
  "home-hero": { scene: "coast", alt: "Antalya sahilinde gün batımında kurumsal bir grup; ufukta Toros dağları" },
  "home-hero-inset": { scene: "sail", alt: "Özel teknede güneşli bir deniz günü; ekip güvertede" },
  "home-venues": { scene: "arches", alt: "Kemerli taş avluda hazırlanmış akşam yemeği masaları" },
  "card-team": { scene: "team", alt: "Plajda takım yarışması sırasında gülen çalışanlar" },
  "card-incentive": { scene: "sail", alt: "Ödül grubu tekne güvertesinde kadeh kaldırıyor" },
  "card-retreat": { scene: "wellness", alt: "Orman kenarında açık havada çalışma masası ve sakin bir ortam" },
  "card-gala": { scene: "gala", alt: "Işıklarla süslenmiş gala salonu, yuvarlak masalar" },
  "card-motivation": { scene: "coast", alt: "Çalışan günü etkinliğinde plajda ortak yemek" },
  "card-outdoor": { scene: "outdoor", alt: "Nehir kenarında rafting ekipmanı ve kask takmış ekip" },
  "card-dealer": { scene: "meeting", alt: "Konferans salonunda bayi toplantısı, ekranda sunum" },
  "card-launch": { scene: "stage", alt: "Spot ışıkları altında lansman sahnesi" },
  "dest-antalya": { scene: "arches", alt: "Kaleiçi'nde taş sokak ve eski liman manzarası" },
  "dest-belek": { scene: "golf", alt: "Belek'te golf sahası, çam ağaçları ve uzakta deniz" },
  "hero-corporate": { scene: "stage", alt: "Kurumsal etkinlik için hazırlanmış sahne ve salon düzeni" },
  "hero-team": { scene: "team", alt: "Takım görevi sırasında birlikte çalışan çalışanlar" },
  "hero-motivation": { scene: "coast", alt: "Plajda çalışan günü; ortak masada gülen ekip" },
  "hero-outdoor": { scene: "outdoor", alt: "Dağ ve nehir manzarasında outdoor grup" },
  "hero-incentive": { scene: "sail", alt: "Incentive grubu özel tekne turunda" },
  "hero-retreat": { scene: "wellness", alt: "Sakin bir ortamda çalışma masası ve doğa görünümü" },
  "hero-gala": { scene: "gala", alt: "Gala gecesi, ışıklı salon ve servise hazır masalar" },
  "hero-dealer": { scene: "meeting", alt: "Bayi toplantısı; salon düzeni ve sahne" },
  "hero-launch": { scene: "stage", alt: "Lansman sahnesi ve ışık tasarımı" },
  "hero-congress": { scene: "meeting", alt: "Kongre salonu, tiyatro düzeni ve ekran" },
  "hero-staff": { scene: "staff", alt: "Etkinlik personeli ekibi, brifing sırasında" },
  "hero-venues": { scene: "arches", alt: "Kemerli bir etkinlik mekânı, akşam ışığında" },
  "hero-antalya": { scene: "coast", alt: "Antalya sahil şeridi ve Toros dağları" },
  "hero-antalya-team": { scene: "team", alt: "Kaleiçi'nde şehir görevi yapan takımlar" },
  "hero-antalya-incentive": { scene: "sail", alt: "Antalya'da tekne turunda incentive grubu" },
  "hero-antalya-retreat": { scene: "wellness", alt: "Kemer çam ormanında sakin bir retreat ortamı" },
  "hero-antalya-outdoor": { scene: "outdoor", alt: "Köprüçay'da rafting yapan ekip" },
  "hero-antalya-venues": { scene: "arches", alt: "Kaleiçi avlusunda kurumsal akşam yemeği" },
  "hero-antalya-staff": { scene: "staff", alt: "Antalya'da çok dilli etkinlik personeli" },
  "hero-belek": { scene: "golf", alt: "Belek'te resort, golf sahası ve plaj" },
  "hero-belek-team": { scene: "golf", alt: "Belek'te golf kliniğinde takımlar" },
  "hero-belek-incentive": { scene: "sail", alt: "Belek'te resort plajında incentive grubu" },
  "hero-belek-retreat": { scene: "wellness", alt: "Belek'te resort bahçesinde sakin bir çalışma ortamı" },
  "hero-belek-venues": { scene: "meeting", alt: "Belek'te resort konferans salonu" },
  "hero-belek-gala": { scene: "gala", alt: "Belek'te plajda kurulu gala masaları, gün batımı" },
  "media-corporate-brief": { scene: "meeting", alt: "Brief toplantısında etkinlik ekibi ve müşteri" },
  "media-team-goal": { scene: "team", alt: "Takım görevinde birlikte karar veren ekip" },
  "media-team-inclusive": { scene: "team", alt: "Farklı rollerde birlikte çalışan çok çeşitli bir ekip" },
  "media-motivation-ritual": { scene: "coast", alt: "Takdir anında alkışlayan çalışanlar" },
  "media-outdoor-safety": { scene: "outdoor", alt: "Güvenlik brifingi veren rehber ve ekip" },
  "media-incentive-reward": { scene: "gala", alt: "Ödül gecesinde kadeh kaldıran grup" },
  "media-incentive-international": { scene: "staff", alt: "Havalimanında isimli karşılama masası" },
  "media-retreat-working": { scene: "wellness", alt: "Doğal ışıklı çalışma salonunda atölye" },
  "media-gala-layers": { scene: "gala", alt: "Gala salonunda sahne, ışık ve masa düzeni" },
  "media-gala-awards": { scene: "stage", alt: "Ödül töreninde sahne ve ışık" },
  "media-dealer-flow": { scene: "meeting", alt: "Bayi toplantısında genel oturum" },
  "media-launch-reveal": { scene: "stage", alt: "Lansman açılış anı; sahne ışıkları" },
  "media-congress-ops": { scene: "meeting", alt: "Kongre kayıt masası ve salon girişi" },
  "media-staff-role": { scene: "staff", alt: "Etkinlik personeli, karşılama masasında" },
  "media-venue-search": { scene: "arches", alt: "Mekân saha ziyareti; kemerli avlu" },
  "media-antalya-oldtown": { scene: "arches", alt: "Kaleiçi'nde taş sokak ve avlu" },
  "media-antalya-citytask": { scene: "arches", alt: "Kaleiçi'nde şehir görevi yapan takım" },
  "media-antalya-incentive-days": { scene: "coast", alt: "Antalya sahilinde gün batımı" },
  "media-antalya-retreat-mood": { scene: "wellness", alt: "Kaleiçi butik otel avlusunda sakin sabah" },
  "media-antalya-route": { scene: "outdoor", alt: "Toros yolunda jeep konvoyu" },
  "media-antalya-venues": { scene: "arches", alt: "Konyaaltı'nda beach club gün batımı" },
  "media-antalya-staff": { scene: "staff", alt: "Antalya'da etkinlik personeli" },
  "media-belek-resort": { scene: "golf", alt: "Belek'te resort ve golf sahası" },
  "media-belek-golf": { scene: "golf", alt: "Golf kliniğinde takımlar" },
  "media-belek-incentive": { scene: "sail", alt: "Belek plajında incentive grubu" },
  "media-belek-retreat": { scene: "wellness", alt: "Resort bahçesinde sabah yürüyüşü" },
  "media-belek-venues": { scene: "meeting", alt: "Belek resort balo salonu" },
  "media-belek-gala": { scene: "gala", alt: "Belek plajında gala kurulumu" },
  "scenario-generic": { scene: "coast", alt: "Örnek etkinlik senaryosu" },
  "scenario-belek-incentive": { scene: "golf", alt: "Belek'te golf turnuvası sonrası plaj akşamı" },
  "scenario-antalya-team": { scene: "arches", alt: "Kaleiçi'nde takım şehir görevi" },
  "scenario-dealer": { scene: "meeting", alt: "Bayi toplantısı genel oturumu" },
  "scenario-dealer-belek": { scene: "meeting", alt: "Belek resort'unda bölge toplantısı" },
  "scenario-antalya-incentive": { scene: "coast", alt: "Antalya sahilinde incentive günü" },
  "scenario-antalya-boat": { scene: "sail", alt: "Kemer'de tekne ve koy günü" },
  "scenario-antalya-meeting": { scene: "meeting", alt: "Şehir otelinde yönetim toplantısı" },
  "scenario-team-city": { scene: "arches", alt: "Şehir görevi sırasında takımlar" },
  "scenario-team-beach": { scene: "coast", alt: "Plaj olimpiyatında takımlar" },
  "scenario-team-cooking": { scene: "table", alt: "Mutfak atölyesinde takımlar" },
  "scenario-motivation-beach": { scene: "coast", alt: "Yıl sonu çalışan günü plajda" },
  "scenario-motivation-sports": { scene: "outdoor", alt: "Vardiyalı spor turnuvasında maç anı" },
  "scenario-motivation-cocktail": { scene: "table", alt: "Kokteyl atölyesinde ekip" },
  "scenario-outdoor-rafting": { scene: "outdoor", alt: "Köprüçay'da rafting" },
  "scenario-outdoor-sail": { scene: "sail", alt: "Kıyıda yelken regatası" },
  "scenario-outdoor-jeep": { scene: "outdoor", alt: "Orman yolunda jeep konvoyu" },
  "scenario-retreat-strategy": { scene: "wellness", alt: "Strateji retreat'i çalışma oturumu" },
  "scenario-retreat-boutique": { scene: "arches", alt: "Butik otel avlusunda atölye" },
  "scenario-gala-beach": { scene: "gala", alt: "Plajda ödül gecesi" },
  "scenario-gala-oldtown": { scene: "arches", alt: "Tarihî avluda gala kokteyli" },
  "scenario-launch-antalya": { scene: "stage", alt: "Antalya'da müşteri lansmanı" },
  "scenario-launch-belek": { scene: "stage", alt: "Belek'te bayi lansmanı" },
  "scenario-belek-spouse": { scene: "wellness", alt: "Eşler için spa ve kültür günü" },
  "scenario-belek-golf": { scene: "golf", alt: "Golf scramble turnuvası" },
  "scenario-belek-garden": { scene: "table", alt: "Resort bahçesinde kokteyl gala'sı" },
  "guide-ideas": { scene: "team", alt: "Etkinlik fikirleri için ekip çalışması" },
  "guide-motivation": { scene: "coast", alt: "Çalışan motivasyonu etkinliği" },
  "guide-team": { scene: "team", alt: "Takım oyunu sırasında ekip" },
  "guide-games": { scene: "team", alt: "Kurumsal oyun sırasında takımlar" },
  "guide-outdoor": { scene: "outdoor", alt: "Doğada kurumsal aktivite" },
  "guide-social": { scene: "table", alt: "Ofis dışında sosyal etkinlik" },
  "guide-antalya-ideas": { scene: "coast", alt: "Antalya'da şirket etkinliği" },
  "guide-belek-team": { scene: "golf", alt: "Belek'te team building" },
  "guide-planning": { scene: "meeting", alt: "Etkinlik planlama toplantısı" },
  "guide-select-team": { scene: "team", alt: "Team building seçimi" },
  "guide-budget": { scene: "meeting", alt: "Etkinlik bütçesi planlaması" },
  "guide-agency": { scene: "meeting", alt: "Ajans ile brief toplantısı" },
  "guide-venues-antalya": { scene: "arches", alt: "Antalya'da etkinlik mekânı" },
  "guide-venues-belek": { scene: "meeting", alt: "Belek'te resort salonu" },
  "guide-antalya-belek": { scene: "coast", alt: "Antalya ve Belek karşılaştırması" },
  "guide-incentive": { scene: "sail", alt: "Incentive ödül seyahati" },
  "guide-retreat": { scene: "wellness", alt: "Corporate retreat" },
  "guide-dealer": { scene: "meeting", alt: "Bayi toplantısı" },
};

export const getSlot = (key: string): Slot => SLOTS[key] ?? { scene: "coast", alt: "" };
